# Generated by Django 4.0.4 on 2023-05-04 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0006_order_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.country')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.CharField(max_length=9999)),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('locations', models.ManyToManyField(to='frontpage.location')),
            ],
        ),
    ]
