# Generated by Django 4.0.4 on 2023-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='opening_time',
            field=models.CharField(default='11:00-23:00', max_length=255),
        ),
    ]
