# Generated by Django 4.0.4 on 2023-05-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_pizza_name_alter_pizzatype_name'),
        ('offers', '0002_alter_offer_image_alter_offer_items_alter_offer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='items',
            field=models.ManyToManyField(to='menu.pizza'),
        ),
    ]
