# Generated by Django 4.0.4 on 2023-05-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_pizza_type'),
        ('offers', '0004_alter_offer_description_alter_offer_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='items',
        ),
        migrations.CreateModel(
            name='OfferItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='menu.pizza')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
            ],
        ),
    ]
