# Generated by Django 4.0.4 on 2023-05-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_offeritems_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeritems',
            name='item_count',
        ),
        migrations.AddField(
            model_name='offeritems',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
