# Generated by Django 4.0.4 on 2023-05-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_pizza_type'),
        ('offers', '0009_remove_offeritems_items_remove_offeritems_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='items',
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='menu.pizza')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
            ],
        ),
    ]
