# Generated by Django 4.0.4 on 2023-05-03 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_pizzaimage_pizza_pizza_images'),
        ('offers', '0010_remove_offer_items_neworder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pizza')),
            ],
        ),
        migrations.AlterField(
            model_name='neworder',
            name='items',
            field=models.ManyToManyField(to='offers.orderitem'),
        ),
    ]
