# Generated by Django 4.0.4 on 2023-05-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_orderitem_alter_neworder_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
