# Generated by Django 4.0.4 on 2023-05-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('userprofile', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('card_number', models.IntegerField()),
                ('cvc', models.IntegerField()),
                ('expiry', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('contact_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.contactinformation')),
                ('credit_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.paymentinformation')),
                ('offers', models.ManyToManyField(to='offers.offer')),
                ('pizzas', models.ManyToManyField(to='menu.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.country'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.user'),
        ),
    ]
