# Generated by Django 4.0.4 on 2023-05-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.contactinformation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='credit_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.paymentinformation'),
        ),
    ]
