# Generated by Django 4.0.4 on 2023-05-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_pizzaimage_pizza_pizza_images'),
        ('offers', '0011_orderitem_alter_neworder_items'),
        ('cart', '0003_alter_order_contact_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.neworder')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='offers',
            field=models.ManyToManyField(to='cart.orderoffer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(to='cart.orderpizza'),
        ),
    ]
