# Generated by Django 4.0.4 on 2023-05-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_contactinformation_user_remove_order_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpizza',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
