# Generated by Django 4.0.4 on 2023-05-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='house_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
