# Generated by Django 4.0.4 on 2023-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_contactinformation_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoffer',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
