# Generated by Django 4.0.4 on 2023-05-09 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_orderoffer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='card_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='cvc',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
