# Generated by Django 4.0.4 on 2023-05-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='review',
            name='payment_info',
        ),
    ]
