# Generated by Django 4.0.4 on 2023-05-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_remove_review_contact_info_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
